export const DISPLAY_TYPE = {
  SUBMIT_ITEM: 'SUBMIT_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  DELETE_ALL: 'DELETE_ALL',
  CHECK_ITEM: 'CHECK_ITEM',
  CHECK_ALL: 'CHECK_ALL',
  UPDATE_DATA: 'UPDATE_DATA',
  UPDATE_FLAG: 'UPDATE_FLAG',
  API_CALL: 'API_CALL',
};
